# coding=utf-8
import numpy as np

"""
Haar Feature TYPE

     --- ---
    |   +   |
    |-------|
    |   -   |
     -------
        I
     --- ---
    |   |   |
    | - | + |
    |   |   |
     --- ---
       II

     -- -- --
    |  |  |  |
    |- | +| -|
    |  |  |  |
     -- -- --
       III

     --- ---
    |___-___|
    |___+___|
    |___-___|
       IV

     --- ---
    | - | + |
    |___|___|
    | + | - |
    |___|___|
        V
"""

class Haar(object):
    def __init__(self, img_width, img_height):
        self.IMG_WIDTH  = img_width
        self.IMG_HEIGHT = img_height

        self.WINDOW_WIDTH  = self.IMG_WIDTH
        self.WINDOW_HEIGHT = self.IMG_HEIGHT

        self.HAAR_TYPES = (
            #'HAAR_TYPE_I',
             'HAAR_TYPE_II',
            # 'HAAR_TYPE_III',
            # 'HAAR_TYPE_IV',
            # 'HAAR_TYPE_V',
            'HAAR_TYPE_6'
        )

        self.features = []
        self._createFeatures()

    def _createFeatures(self):
        """create all kinds of haar features in this window size
        :return: [(h_type, x, y, w, h),
                  (h_type, x, y, w, h),
                  ...]
                  notice: x,y are the coordinates in the image Matrix instead of the integral image Matrix
        """

        WIDTH_LIMIT  = {
            #"HAAR_TYPE_I"   : self.WINDOW_WIDTH,
             "HAAR_TYPE_II"  : int(self.WINDOW_WIDTH/2),
            # "HAAR_TYPE_III" : int(self.WINDOW_WIDTH/3),
            # "HAAR_TYPE_IV"  : self.WINDOW_WIDTH,
            #"HAAR_TYPE_V"   : int(self.WINDOW_WIDTH/2),
            "HAAR_TYPE_6": int(self.WINDOW_WIDTH / 20)
        }

        HEIGHT_LIMIT = {
            #"HAAR_TYPE_I"   : int(self.WINDOW_HEIGHT/2),
            "HAAR_TYPE_II"  : self.WINDOW_HEIGHT,
            # "HAAR_TYPE_III" : self.WINDOW_HEIGHT,
            # "HAAR_TYPE_IV"  : int(self.WINDOW_HEIGHT/3),
            # "HAAR_TYPE_V"   : int(self.WINDOW_HEIGHT/2),
            "HAAR_TYPE_6": int(self.WINDOW_HEIGHT / 35)
        }

        for h_type in self.HAAR_TYPES:
            for w in range(1, WIDTH_LIMIT[h_type]+1):
                for h in range(1, HEIGHT_LIMIT[h_type]+1):

                    # if h_type == "HAAR_TYPE_I":
                    #     x_limit = self.WINDOW_WIDTH  - w
                    #     y_limit = self.WINDOW_HEIGHT - 2*h
                    #
                    #     for x in range(0, x_limit+1):
                    #         for y in range(0, y_limit+1):
                    #             self.features.append([h_type, x, y, w, h])

                    if h_type == "HAAR_TYPE_II":
                        x_limit = self.WINDOW_WIDTH - 2*w
                        y_limit = self.WINDOW_HEIGHT - h

                    #     for x in range(0, x_limit+1):
                    #         for y in range(0, y_limit+1):
                    #             self.features.append([h_type, x, y, w, h])
                    #
                    # if h_type == "HAAR_TYPE_III":
                    #     x_limit = self.WINDOW_WIDTH - 3*w
                    #     y_limit = self.WINDOW_HEIGHT - h
                    #
                    #     for x in range(0, x_limit+1):
                    #         for y in range(0, y_limit+1):
                    #             self.features.append([h_type, x, y, w, h])
                    #
                    # if h_type == "HAAR_TYPE_IV":
                    #     x_limit = self.WINDOW_WIDTH - w
                    #     y_limit = self.WINDOW_HEIGHT - 3*h
                    #
                    #     for x in range(0, x_limit+1):
                    #         for y in range(0, y_limit+1):
                    #             self.features.append([h_type, x, y, w, h])
                    #
                    # if h_type == "HAAR_TYPE_V":
                    #     x_limit = self.WINDOW_WIDTH - 2*w
                    #     y_limit = self.WINDOW_HEIGHT - 2*h
                    #
                    #     for x in range(0, x_limit+1):
                    #         for y in range(0, y_limit+1):
                    #             self.features.append([h_type, x, y, w, h])

                    if h_type == "HAAR_TYPE_6":
                        x_limit = self.WINDOW_WIDTH - 20*w
                        y_limit = self.WINDOW_HEIGHT - 35*h

                        for x in range(0, x_limit+1):
                            for y in range(0, y_limit+1):
                                self.features.append([h_type, x, y, w, h])

    def calImgFeatureVal(self, IntegralMat, mat):
        """
        :param IntegralMat: the integral value of the image
        :return: a list including values of all features
        """
        featureVal = np.zeros(len(self.features))

        for feature_index in range(len(self.features)):
            h_type, x, y, w, h = self.features[feature_index]

            # #normalization
            # sumVal        = sum(sum(mat[y:y+h, x:x+w]))
            # sqSumVal      = sum(sum(mat[y:y+h, x:x+w] ** 2))
            # meanVal       = sumVal   / (w * h)
            # sqMeanVal     = sqSumVal / (w * h)
            #
            # normFactorVal = np.sqrt(sqMeanVal - meanVal ** 2)
            # if normFactorVal == 0:
            #     normFactorVal = 1


            # if h_type == "HAAR_TYPE_I":
            #     pos = self.getPixelValInIntegralMat(x, y, w, h, IntegralMat)
            #     neg = self.getPixelValInIntegralMat(x, y+h, w, h, IntegralMat)
            #
            #     featureVal[feature_index] = (pos - neg) / (2 * w * h)
            if h_type == "HAAR_TYPE_II":
                neg = self.getPixelValInIntegralMat(x,   y, w, h, IntegralMat)
                pos = self.getPixelValInIntegralMat(x+w, y, w, h, IntegralMat)

                featureVal[feature_index] = (pos - neg) / (2 * w * h)
            # elif h_type == "HAAR_TYPE_III":
            #     neg1 = self.getPixelValInIntegralMat(x, y, w, h, IntegralMat)
            #     pos  = self.getPixelValInIntegralMat(x+w, y, w, h, IntegralMat)
            #     neg2 = self.getPixelValInIntegralMat(x+2*w, y, w, h, IntegralMat)
            #
            #     featureVal[feature_index] = (2*pos - neg1 - neg2)/ (3 * w * h)
            #
            # elif h_type == "HAAR_TYPE_IV":
            #     neg1 = self.getPixelValInIntegralMat(x, y, w, h, IntegralMat)
            #     pos  = self.getPixelValInIntegralMat(x, y+h, w, h, IntegralMat)
            #     neg2 = self.getPixelValInIntegralMat(x, y+2*h, w, h, IntegralMat)
            #
            #     featureVal[feature_index] = (2*pos - neg1 - neg2) / (3 * w * h)
            #
            # elif h_type == "HAAR_TYPE_V":
            #     neg1 = self.getPixelValInIntegralMat(x, y, w, h, IntegralMat)
            #     pos1 = self.getPixelValInIntegralMat(x+w, y, w, h, IntegralMat)
            #     pos2 = self.getPixelValInIntegralMat(x, y+h, w, h, IntegralMat)
            #     neg2 = self.getPixelValInIntegralMat(x+w, y+h, w, h, IntegralMat)
            #
            #     featureVal[feature_index] = (pos1 + pos2 - neg1 - neg2) / (4 * w * h)

            elif h_type == "HAAR_TYPE_6":
                neg00 = self.getPixelValInIntegralMat(x + 0 * w, y + 0 * h, w, h, IntegralMat)
                neg10 = self.getPixelValInIntegralMat(x + 1 * w, y + 0 * h, w, h, IntegralMat)
                neg20 = self.getPixelValInIntegralMat(x + 2 * w, y + 0 * h, w, h, IntegralMat)
                neg30 = self.getPixelValInIntegralMat(x + 3 * w, y + 0 * h, w, h, IntegralMat)
                neg40 = self.getPixelValInIntegralMat(x + 4 * w, y + 0 * h, w, h, IntegralMat)
                neg50 = self.getPixelValInIntegralMat(x + 5 * w, y + 0 * h, w, h, IntegralMat)
                neg60 = self.getPixelValInIntegralMat(x + 6 * w, y + 0 * h, w, h, IntegralMat)
                neg70 = self.getPixelValInIntegralMat(x + 7 * w, y + 0 * h, w, h, IntegralMat)
                neg80 = self.getPixelValInIntegralMat(x + 8 * w, y + 0 * h, w, h, IntegralMat)
                neg90 = self.getPixelValInIntegralMat(x + 9 * w, y + 0 * h, w, h, IntegralMat)
                neg100 = self.getPixelValInIntegralMat(x + 10 * w, y + 0 * h, w, h, IntegralMat)
                neg110 = self.getPixelValInIntegralMat(x + 11 * w, y + 0 * h, w, h, IntegralMat)
                neg120 = self.getPixelValInIntegralMat(x + 12 * w, y + 0 * h, w, h, IntegralMat)
                neg130 = self.getPixelValInIntegralMat(x + 13 * w, y + 0 * h, w, h, IntegralMat)
                neg140 = self.getPixelValInIntegralMat(x + 14 * w, y + 0 * h, w, h, IntegralMat)
                neg150 = self.getPixelValInIntegralMat(x + 15 * w, y + 0 * h, w, h, IntegralMat)
                neg160 = self.getPixelValInIntegralMat(x + 16 * w, y + 0 * h, w, h, IntegralMat)
                neg170 = self.getPixelValInIntegralMat(x + 17 * w, y + 0 * h, w, h, IntegralMat)
                neg180 = self.getPixelValInIntegralMat(x + 18 * w, y + 0 * h, w, h, IntegralMat)
                neg190 = self.getPixelValInIntegralMat(x + 19 * w, y + 0 * h, w, h, IntegralMat)
                neg01 = self.getPixelValInIntegralMat(x + 0 * w, y + 1 * h, w, h, IntegralMat)
                neg11 = self.getPixelValInIntegralMat(x + 1 * w, y + 1 * h, w, h, IntegralMat)
                neg21 = self.getPixelValInIntegralMat(x + 2 * w, y + 1 * h, w, h, IntegralMat)
                neg31 = self.getPixelValInIntegralMat(x + 3 * w, y + 1 * h, w, h, IntegralMat)
                neg41 = self.getPixelValInIntegralMat(x + 4 * w, y + 1 * h, w, h, IntegralMat)
                neg51 = self.getPixelValInIntegralMat(x + 5 * w, y + 1 * h, w, h, IntegralMat)
                neg61 = self.getPixelValInIntegralMat(x + 6 * w, y + 1 * h, w, h, IntegralMat)
                neg71 = self.getPixelValInIntegralMat(x + 7 * w, y + 1 * h, w, h, IntegralMat)
                neg81 = self.getPixelValInIntegralMat(x + 8 * w, y + 1 * h, w, h, IntegralMat)
                neg91 = self.getPixelValInIntegralMat(x + 9 * w, y + 1 * h, w, h, IntegralMat)
                neg101 = self.getPixelValInIntegralMat(x + 10 * w, y + 1 * h, w, h, IntegralMat)
                neg111 = self.getPixelValInIntegralMat(x + 11 * w, y + 1 * h, w, h, IntegralMat)
                neg121 = self.getPixelValInIntegralMat(x + 12 * w, y + 1 * h, w, h, IntegralMat)
                neg131 = self.getPixelValInIntegralMat(x + 13 * w, y + 1 * h, w, h, IntegralMat)
                neg141 = self.getPixelValInIntegralMat(x + 14 * w, y + 1 * h, w, h, IntegralMat)
                neg151 = self.getPixelValInIntegralMat(x + 15 * w, y + 1 * h, w, h, IntegralMat)
                neg161 = self.getPixelValInIntegralMat(x + 16 * w, y + 1 * h, w, h, IntegralMat)
                neg171 = self.getPixelValInIntegralMat(x + 17 * w, y + 1 * h, w, h, IntegralMat)
                neg181 = self.getPixelValInIntegralMat(x + 18 * w, y + 1 * h, w, h, IntegralMat)
                neg191 = self.getPixelValInIntegralMat(x + 19 * w, y + 1 * h, w, h, IntegralMat)
                neg02 = self.getPixelValInIntegralMat(x + 0 * w, y + 2 * h, w, h, IntegralMat)
                neg12 = self.getPixelValInIntegralMat(x + 1 * w, y + 2 * h, w, h, IntegralMat)
                neg22 = self.getPixelValInIntegralMat(x + 2 * w, y + 2 * h, w, h, IntegralMat)
                neg32 = self.getPixelValInIntegralMat(x + 3 * w, y + 2 * h, w, h, IntegralMat)
                neg42 = self.getPixelValInIntegralMat(x + 4 * w, y + 2 * h, w, h, IntegralMat)
                neg52 = self.getPixelValInIntegralMat(x + 5 * w, y + 2 * h, w, h, IntegralMat)
                neg62 = self.getPixelValInIntegralMat(x + 6 * w, y + 2 * h, w, h, IntegralMat)
                neg72 = self.getPixelValInIntegralMat(x + 7 * w, y + 2 * h, w, h, IntegralMat)
                pos82 = self.getPixelValInIntegralMat(x + 8 * w, y + 2 * h, w, h, IntegralMat)
                pos92 = self.getPixelValInIntegralMat(x + 9 * w, y + 2 * h, w, h, IntegralMat)
                neg102 = self.getPixelValInIntegralMat(x + 10 * w, y + 2 * h, w, h, IntegralMat)
                neg112 = self.getPixelValInIntegralMat(x + 11 * w, y + 2 * h, w, h, IntegralMat)
                neg122 = self.getPixelValInIntegralMat(x + 12 * w, y + 2 * h, w, h, IntegralMat)
                neg132 = self.getPixelValInIntegralMat(x + 13 * w, y + 2 * h, w, h, IntegralMat)
                neg142 = self.getPixelValInIntegralMat(x + 14 * w, y + 2 * h, w, h, IntegralMat)
                neg152 = self.getPixelValInIntegralMat(x + 15 * w, y + 2 * h, w, h, IntegralMat)
                neg162 = self.getPixelValInIntegralMat(x + 16 * w, y + 2 * h, w, h, IntegralMat)
                neg172 = self.getPixelValInIntegralMat(x + 17 * w, y + 2 * h, w, h, IntegralMat)
                neg182 = self.getPixelValInIntegralMat(x + 18 * w, y + 2 * h, w, h, IntegralMat)
                neg192 = self.getPixelValInIntegralMat(x + 19 * w, y + 2 * h, w, h, IntegralMat)
                neg03 = self.getPixelValInIntegralMat(x + 0 * w, y + 3 * h, w, h, IntegralMat)
                neg13 = self.getPixelValInIntegralMat(x + 1 * w, y + 3 * h, w, h, IntegralMat)
                neg23 = self.getPixelValInIntegralMat(x + 2 * w, y + 3 * h, w, h, IntegralMat)
                neg33 = self.getPixelValInIntegralMat(x + 3 * w, y + 3 * h, w, h, IntegralMat)
                neg43 = self.getPixelValInIntegralMat(x + 4 * w, y + 3 * h, w, h, IntegralMat)
                neg53 = self.getPixelValInIntegralMat(x + 5 * w, y + 3 * h, w, h, IntegralMat)
                neg63 = self.getPixelValInIntegralMat(x + 6 * w, y + 3 * h, w, h, IntegralMat)
                pos73 = self.getPixelValInIntegralMat(x + 7 * w, y + 3 * h, w, h, IntegralMat)
                pos83 = self.getPixelValInIntegralMat(x + 8 * w, y + 3 * h, w, h, IntegralMat)
                pos93 = self.getPixelValInIntegralMat(x + 9 * w, y + 3 * h, w, h, IntegralMat)
                pos103 = self.getPixelValInIntegralMat(x + 10 * w, y + 3 * h, w, h, IntegralMat)
                neg113 = self.getPixelValInIntegralMat(x + 11 * w, y + 3 * h, w, h, IntegralMat)
                neg123 = self.getPixelValInIntegralMat(x + 12 * w, y + 3 * h, w, h, IntegralMat)
                neg133 = self.getPixelValInIntegralMat(x + 13 * w, y + 3 * h, w, h, IntegralMat)
                neg143 = self.getPixelValInIntegralMat(x + 14 * w, y + 3 * h, w, h, IntegralMat)
                neg153 = self.getPixelValInIntegralMat(x + 15 * w, y + 3 * h, w, h, IntegralMat)
                neg163 = self.getPixelValInIntegralMat(x + 16 * w, y + 3 * h, w, h, IntegralMat)
                neg173 = self.getPixelValInIntegralMat(x + 17 * w, y + 3 * h, w, h, IntegralMat)
                neg183 = self.getPixelValInIntegralMat(x + 18 * w, y + 3 * h, w, h, IntegralMat)
                neg193 = self.getPixelValInIntegralMat(x + 19 * w, y + 3 * h, w, h, IntegralMat)
                neg04 = self.getPixelValInIntegralMat(x + 0 * w, y + 4 * h, w, h, IntegralMat)
                neg14 = self.getPixelValInIntegralMat(x + 1 * w, y + 4 * h, w, h, IntegralMat)
                neg24 = self.getPixelValInIntegralMat(x + 2 * w, y + 4 * h, w, h, IntegralMat)
                neg34 = self.getPixelValInIntegralMat(x + 3 * w, y + 4 * h, w, h, IntegralMat)
                neg44 = self.getPixelValInIntegralMat(x + 4 * w, y + 4 * h, w, h, IntegralMat)
                neg54 = self.getPixelValInIntegralMat(x + 5 * w, y + 4 * h, w, h, IntegralMat)
                neg64 = self.getPixelValInIntegralMat(x + 6 * w, y + 4 * h, w, h, IntegralMat)
                pos74 = self.getPixelValInIntegralMat(x + 7 * w, y + 4 * h, w, h, IntegralMat)
                pos84 = self.getPixelValInIntegralMat(x + 8 * w, y + 4 * h, w, h, IntegralMat)
                pos94 = self.getPixelValInIntegralMat(x + 9 * w, y + 4 * h, w, h, IntegralMat)
                pos104 = self.getPixelValInIntegralMat(x + 10 * w, y + 4 * h, w, h, IntegralMat)
                neg114 = self.getPixelValInIntegralMat(x + 11 * w, y + 4 * h, w, h, IntegralMat)
                neg124 = self.getPixelValInIntegralMat(x + 12 * w, y + 4 * h, w, h, IntegralMat)
                neg134 = self.getPixelValInIntegralMat(x + 13 * w, y + 4 * h, w, h, IntegralMat)
                neg144 = self.getPixelValInIntegralMat(x + 14 * w, y + 4 * h, w, h, IntegralMat)
                neg154 = self.getPixelValInIntegralMat(x + 15 * w, y + 4 * h, w, h, IntegralMat)
                neg164 = self.getPixelValInIntegralMat(x + 16 * w, y + 4 * h, w, h, IntegralMat)
                neg174 = self.getPixelValInIntegralMat(x + 17 * w, y + 4 * h, w, h, IntegralMat)
                neg184 = self.getPixelValInIntegralMat(x + 18 * w, y + 4 * h, w, h, IntegralMat)
                neg194 = self.getPixelValInIntegralMat(x + 19 * w, y + 4 * h, w, h, IntegralMat)
                neg05 = self.getPixelValInIntegralMat(x + 0 * w, y + 5 * h, w, h, IntegralMat)
                neg15 = self.getPixelValInIntegralMat(x + 1 * w, y + 5 * h, w, h, IntegralMat)
                neg25 = self.getPixelValInIntegralMat(x + 2 * w, y + 5 * h, w, h, IntegralMat)
                neg35 = self.getPixelValInIntegralMat(x + 3 * w, y + 5 * h, w, h, IntegralMat)
                neg45 = self.getPixelValInIntegralMat(x + 4 * w, y + 5 * h, w, h, IntegralMat)
                neg55 = self.getPixelValInIntegralMat(x + 5 * w, y + 5 * h, w, h, IntegralMat)
                pos65 = self.getPixelValInIntegralMat(x + 6 * w, y + 5 * h, w, h, IntegralMat)
                pos75 = self.getPixelValInIntegralMat(x + 7 * w, y + 5 * h, w, h, IntegralMat)
                pos85 = self.getPixelValInIntegralMat(x + 8 * w, y + 5 * h, w, h, IntegralMat)
                pos95 = self.getPixelValInIntegralMat(x + 9 * w, y + 5 * h, w, h, IntegralMat)
                pos105 = self.getPixelValInIntegralMat(x + 10 * w, y + 5 * h, w, h, IntegralMat)
                neg115 = self.getPixelValInIntegralMat(x + 11 * w, y + 5 * h, w, h, IntegralMat)
                neg125 = self.getPixelValInIntegralMat(x + 12 * w, y + 5 * h, w, h, IntegralMat)
                neg135 = self.getPixelValInIntegralMat(x + 13 * w, y + 5 * h, w, h, IntegralMat)
                neg145 = self.getPixelValInIntegralMat(x + 14 * w, y + 5 * h, w, h, IntegralMat)
                neg155 = self.getPixelValInIntegralMat(x + 15 * w, y + 5 * h, w, h, IntegralMat)
                neg165 = self.getPixelValInIntegralMat(x + 16 * w, y + 5 * h, w, h, IntegralMat)
                neg175 = self.getPixelValInIntegralMat(x + 17 * w, y + 5 * h, w, h, IntegralMat)
                neg185 = self.getPixelValInIntegralMat(x + 18 * w, y + 5 * h, w, h, IntegralMat)
                neg195 = self.getPixelValInIntegralMat(x + 19 * w, y + 5 * h, w, h, IntegralMat)
                neg06 = self.getPixelValInIntegralMat(x + 0 * w, y + 6 * h, w, h, IntegralMat)
                neg16 = self.getPixelValInIntegralMat(x + 1 * w, y + 6 * h, w, h, IntegralMat)
                neg26 = self.getPixelValInIntegralMat(x + 2 * w, y + 6 * h, w, h, IntegralMat)
                neg36 = self.getPixelValInIntegralMat(x + 3 * w, y + 6 * h, w, h, IntegralMat)
                neg46 = self.getPixelValInIntegralMat(x + 4 * w, y + 6 * h, w, h, IntegralMat)
                pos56 = self.getPixelValInIntegralMat(x + 5 * w, y + 6 * h, w, h, IntegralMat)
                pos66 = self.getPixelValInIntegralMat(x + 6 * w, y + 6 * h, w, h, IntegralMat)
                pos76 = self.getPixelValInIntegralMat(x + 7 * w, y + 6 * h, w, h, IntegralMat)
                pos86 = self.getPixelValInIntegralMat(x + 8 * w, y + 6 * h, w, h, IntegralMat)
                pos96 = self.getPixelValInIntegralMat(x + 9 * w, y + 6 * h, w, h, IntegralMat)
                pos106 = self.getPixelValInIntegralMat(x + 10 * w, y + 6 * h, w, h, IntegralMat)
                neg116 = self.getPixelValInIntegralMat(x + 11 * w, y + 6 * h, w, h, IntegralMat)
                neg126 = self.getPixelValInIntegralMat(x + 12 * w, y + 6 * h, w, h, IntegralMat)
                neg136 = self.getPixelValInIntegralMat(x + 13 * w, y + 6 * h, w, h, IntegralMat)
                neg146 = self.getPixelValInIntegralMat(x + 14 * w, y + 6 * h, w, h, IntegralMat)
                neg156 = self.getPixelValInIntegralMat(x + 15 * w, y + 6 * h, w, h, IntegralMat)
                neg166 = self.getPixelValInIntegralMat(x + 16 * w, y + 6 * h, w, h, IntegralMat)
                neg176 = self.getPixelValInIntegralMat(x + 17 * w, y + 6 * h, w, h, IntegralMat)
                neg186 = self.getPixelValInIntegralMat(x + 18 * w, y + 6 * h, w, h, IntegralMat)
                neg196 = self.getPixelValInIntegralMat(x + 19 * w, y + 6 * h, w, h, IntegralMat)
                neg07 = self.getPixelValInIntegralMat(x + 0 * w, y + 7 * h, w, h, IntegralMat)
                neg17 = self.getPixelValInIntegralMat(x + 1 * w, y + 7 * h, w, h, IntegralMat)
                neg27 = self.getPixelValInIntegralMat(x + 2 * w, y + 7 * h, w, h, IntegralMat)
                neg37 = self.getPixelValInIntegralMat(x + 3 * w, y + 7 * h, w, h, IntegralMat)
                neg47 = self.getPixelValInIntegralMat(x + 4 * w, y + 7 * h, w, h, IntegralMat)
                pos57 = self.getPixelValInIntegralMat(x + 5 * w, y + 7 * h, w, h, IntegralMat)
                pos67 = self.getPixelValInIntegralMat(x + 6 * w, y + 7 * h, w, h, IntegralMat)
                pos77 = self.getPixelValInIntegralMat(x + 7 * w, y + 7 * h, w, h, IntegralMat)
                pos87 = self.getPixelValInIntegralMat(x + 8 * w, y + 7 * h, w, h, IntegralMat)
                pos97 = self.getPixelValInIntegralMat(x + 9 * w, y + 7 * h, w, h, IntegralMat)
                pos107 = self.getPixelValInIntegralMat(x + 10 * w, y + 7 * h, w, h, IntegralMat)
                pos117 = self.getPixelValInIntegralMat(x + 11 * w, y + 7 * h, w, h, IntegralMat)
                pos127 = self.getPixelValInIntegralMat(x + 12 * w, y + 7 * h, w, h, IntegralMat)
                neg137 = self.getPixelValInIntegralMat(x + 13 * w, y + 7 * h, w, h, IntegralMat)
                neg147 = self.getPixelValInIntegralMat(x + 14 * w, y + 7 * h, w, h, IntegralMat)
                neg157 = self.getPixelValInIntegralMat(x + 15 * w, y + 7 * h, w, h, IntegralMat)
                neg167 = self.getPixelValInIntegralMat(x + 16 * w, y + 7 * h, w, h, IntegralMat)
                neg177 = self.getPixelValInIntegralMat(x + 17 * w, y + 7 * h, w, h, IntegralMat)
                neg187 = self.getPixelValInIntegralMat(x + 18 * w, y + 7 * h, w, h, IntegralMat)
                neg197 = self.getPixelValInIntegralMat(x + 19 * w, y + 7 * h, w, h, IntegralMat)
                neg08 = self.getPixelValInIntegralMat(x + 0 * w, y + 8 * h, w, h, IntegralMat)
                neg18 = self.getPixelValInIntegralMat(x + 1 * w, y + 8 * h, w, h, IntegralMat)
                neg28 = self.getPixelValInIntegralMat(x + 2 * w, y + 8 * h, w, h, IntegralMat)
                neg38 = self.getPixelValInIntegralMat(x + 3 * w, y + 8 * h, w, h, IntegralMat)
                neg48 = self.getPixelValInIntegralMat(x + 4 * w, y + 8 * h, w, h, IntegralMat)
                pos58 = self.getPixelValInIntegralMat(x + 5 * w, y + 8 * h, w, h, IntegralMat)
                pos68 = self.getPixelValInIntegralMat(x + 6 * w, y + 8 * h, w, h, IntegralMat)
                pos78 = self.getPixelValInIntegralMat(x + 7 * w, y + 8 * h, w, h, IntegralMat)
                pos88 = self.getPixelValInIntegralMat(x + 8 * w, y + 8 * h, w, h, IntegralMat)
                pos98 = self.getPixelValInIntegralMat(x + 9 * w, y + 8 * h, w, h, IntegralMat)
                pos108 = self.getPixelValInIntegralMat(x + 10 * w, y + 8 * h, w, h, IntegralMat)
                pos118 = self.getPixelValInIntegralMat(x + 11 * w, y + 8 * h, w, h, IntegralMat)
                pos128 = self.getPixelValInIntegralMat(x + 12 * w, y + 8 * h, w, h, IntegralMat)
                pos138 = self.getPixelValInIntegralMat(x + 13 * w, y + 8 * h, w, h, IntegralMat)
                pos148 = self.getPixelValInIntegralMat(x + 14 * w, y + 8 * h, w, h, IntegralMat)
                neg158 = self.getPixelValInIntegralMat(x + 15 * w, y + 8 * h, w, h, IntegralMat)
                neg168 = self.getPixelValInIntegralMat(x + 16 * w, y + 8 * h, w, h, IntegralMat)
                neg178 = self.getPixelValInIntegralMat(x + 17 * w, y + 8 * h, w, h, IntegralMat)
                neg188 = self.getPixelValInIntegralMat(x + 18 * w, y + 8 * h, w, h, IntegralMat)
                neg198 = self.getPixelValInIntegralMat(x + 19 * w, y + 8 * h, w, h, IntegralMat)
                neg09 = self.getPixelValInIntegralMat(x + 0 * w, y + 9 * h, w, h, IntegralMat)
                neg19 = self.getPixelValInIntegralMat(x + 1 * w, y + 9 * h, w, h, IntegralMat)
                neg29 = self.getPixelValInIntegralMat(x + 2 * w, y + 9 * h, w, h, IntegralMat)
                neg39 = self.getPixelValInIntegralMat(x + 3 * w, y + 9 * h, w, h, IntegralMat)
                pos49 = self.getPixelValInIntegralMat(x + 4 * w, y + 9 * h, w, h, IntegralMat)
                pos59 = self.getPixelValInIntegralMat(x + 5 * w, y + 9 * h, w, h, IntegralMat)
                pos69 = self.getPixelValInIntegralMat(x + 6 * w, y + 9 * h, w, h, IntegralMat)
                pos79 = self.getPixelValInIntegralMat(x + 7 * w, y + 9 * h, w, h, IntegralMat)
                pos89 = self.getPixelValInIntegralMat(x + 8 * w, y + 9 * h, w, h, IntegralMat)
                pos99 = self.getPixelValInIntegralMat(x + 9 * w, y + 9 * h, w, h, IntegralMat)
                pos109 = self.getPixelValInIntegralMat(x + 10 * w, y + 9 * h, w, h, IntegralMat)
                pos119 = self.getPixelValInIntegralMat(x + 11 * w, y + 9 * h, w, h, IntegralMat)
                pos129 = self.getPixelValInIntegralMat(x + 12 * w, y + 9 * h, w, h, IntegralMat)
                pos139 = self.getPixelValInIntegralMat(x + 13 * w, y + 9 * h, w, h, IntegralMat)
                pos149 = self.getPixelValInIntegralMat(x + 14 * w, y + 9 * h, w, h, IntegralMat)
                neg159 = self.getPixelValInIntegralMat(x + 15 * w, y + 9 * h, w, h, IntegralMat)
                neg169 = self.getPixelValInIntegralMat(x + 16 * w, y + 9 * h, w, h, IntegralMat)
                neg179 = self.getPixelValInIntegralMat(x + 17 * w, y + 9 * h, w, h, IntegralMat)
                neg189 = self.getPixelValInIntegralMat(x + 18 * w, y + 9 * h, w, h, IntegralMat)
                neg199 = self.getPixelValInIntegralMat(x + 19 * w, y + 9 * h, w, h, IntegralMat)
                neg010 = self.getPixelValInIntegralMat(x + 0 * w, y + 10 * h, w, h, IntegralMat)
                neg110 = self.getPixelValInIntegralMat(x + 1 * w, y + 10 * h, w, h, IntegralMat)
                neg210 = self.getPixelValInIntegralMat(x + 2 * w, y + 10 * h, w, h, IntegralMat)
                neg310 = self.getPixelValInIntegralMat(x + 3 * w, y + 10 * h, w, h, IntegralMat)
                pos410 = self.getPixelValInIntegralMat(x + 4 * w, y + 10 * h, w, h, IntegralMat)
                pos510 = self.getPixelValInIntegralMat(x + 5 * w, y + 10 * h, w, h, IntegralMat)
                pos610 = self.getPixelValInIntegralMat(x + 6 * w, y + 10 * h, w, h, IntegralMat)
                pos710 = self.getPixelValInIntegralMat(x + 7 * w, y + 10 * h, w, h, IntegralMat)
                pos810 = self.getPixelValInIntegralMat(x + 8 * w, y + 10 * h, w, h, IntegralMat)
                pos910 = self.getPixelValInIntegralMat(x + 9 * w, y + 10 * h, w, h, IntegralMat)
                pos1010 = self.getPixelValInIntegralMat(x + 10 * w, y + 10 * h, w, h, IntegralMat)
                pos1110 = self.getPixelValInIntegralMat(x + 11 * w, y + 10 * h, w, h, IntegralMat)
                pos1210 = self.getPixelValInIntegralMat(x + 12 * w, y + 10 * h, w, h, IntegralMat)
                pos1310 = self.getPixelValInIntegralMat(x + 13 * w, y + 10 * h, w, h, IntegralMat)
                pos1410 = self.getPixelValInIntegralMat(x + 14 * w, y + 10 * h, w, h, IntegralMat)
                neg1510 = self.getPixelValInIntegralMat(x + 15 * w, y + 10 * h, w, h, IntegralMat)
                neg1610 = self.getPixelValInIntegralMat(x + 16 * w, y + 10 * h, w, h, IntegralMat)
                neg1710 = self.getPixelValInIntegralMat(x + 17 * w, y + 10 * h, w, h, IntegralMat)
                neg1810 = self.getPixelValInIntegralMat(x + 18 * w, y + 10 * h, w, h, IntegralMat)
                neg1910 = self.getPixelValInIntegralMat(x + 19 * w, y + 10 * h, w, h, IntegralMat)
                neg011 = self.getPixelValInIntegralMat(x + 0 * w, y + 11 * h, w, h, IntegralMat)
                neg111 = self.getPixelValInIntegralMat(x + 1 * w, y + 11 * h, w, h, IntegralMat)
                neg211 = self.getPixelValInIntegralMat(x + 2 * w, y + 11 * h, w, h, IntegralMat)
                neg311 = self.getPixelValInIntegralMat(x + 3 * w, y + 11 * h, w, h, IntegralMat)
                pos411 = self.getPixelValInIntegralMat(x + 4 * w, y + 11 * h, w, h, IntegralMat)
                pos511 = self.getPixelValInIntegralMat(x + 5 * w, y + 11 * h, w, h, IntegralMat)
                pos611 = self.getPixelValInIntegralMat(x + 6 * w, y + 11 * h, w, h, IntegralMat)
                pos711 = self.getPixelValInIntegralMat(x + 7 * w, y + 11 * h, w, h, IntegralMat)
                pos811 = self.getPixelValInIntegralMat(x + 8 * w, y + 11 * h, w, h, IntegralMat)
                pos911 = self.getPixelValInIntegralMat(x + 9 * w, y + 11 * h, w, h, IntegralMat)
                pos1011 = self.getPixelValInIntegralMat(x + 10 * w, y + 11 * h, w, h, IntegralMat)
                pos1111 = self.getPixelValInIntegralMat(x + 11 * w, y + 11 * h, w, h, IntegralMat)
                pos1211 = self.getPixelValInIntegralMat(x + 12 * w, y + 11 * h, w, h, IntegralMat)
                pos1311 = self.getPixelValInIntegralMat(x + 13 * w, y + 11 * h, w, h, IntegralMat)
                pos1411 = self.getPixelValInIntegralMat(x + 14 * w, y + 11 * h, w, h, IntegralMat)
                neg1511 = self.getPixelValInIntegralMat(x + 15 * w, y + 11 * h, w, h, IntegralMat)
                neg1611 = self.getPixelValInIntegralMat(x + 16 * w, y + 11 * h, w, h, IntegralMat)
                neg1711 = self.getPixelValInIntegralMat(x + 17 * w, y + 11 * h, w, h, IntegralMat)
                neg1811 = self.getPixelValInIntegralMat(x + 18 * w, y + 11 * h, w, h, IntegralMat)
                neg1911 = self.getPixelValInIntegralMat(x + 19 * w, y + 11 * h, w, h, IntegralMat)
                neg012 = self.getPixelValInIntegralMat(x + 0 * w, y + 12 * h, w, h, IntegralMat)
                neg112 = self.getPixelValInIntegralMat(x + 1 * w, y + 12 * h, w, h, IntegralMat)
                neg212 = self.getPixelValInIntegralMat(x + 2 * w, y + 12 * h, w, h, IntegralMat)
                neg312 = self.getPixelValInIntegralMat(x + 3 * w, y + 12 * h, w, h, IntegralMat)
                pos412 = self.getPixelValInIntegralMat(x + 4 * w, y + 12 * h, w, h, IntegralMat)
                pos512 = self.getPixelValInIntegralMat(x + 5 * w, y + 12 * h, w, h, IntegralMat)
                pos612 = self.getPixelValInIntegralMat(x + 6 * w, y + 12 * h, w, h, IntegralMat)
                pos712 = self.getPixelValInIntegralMat(x + 7 * w, y + 12 * h, w, h, IntegralMat)
                pos812 = self.getPixelValInIntegralMat(x + 8 * w, y + 12 * h, w, h, IntegralMat)
                pos912 = self.getPixelValInIntegralMat(x + 9 * w, y + 12 * h, w, h, IntegralMat)
                pos1012 = self.getPixelValInIntegralMat(x + 10 * w, y + 12 * h, w, h, IntegralMat)
                pos1112 = self.getPixelValInIntegralMat(x + 11 * w, y + 12 * h, w, h, IntegralMat)
                pos1212 = self.getPixelValInIntegralMat(x + 12 * w, y + 12 * h, w, h, IntegralMat)
                pos1312 = self.getPixelValInIntegralMat(x + 13 * w, y + 12 * h, w, h, IntegralMat)
                neg1412 = self.getPixelValInIntegralMat(x + 14 * w, y + 12 * h, w, h, IntegralMat)
                neg1512 = self.getPixelValInIntegralMat(x + 15 * w, y + 12 * h, w, h, IntegralMat)
                neg1612 = self.getPixelValInIntegralMat(x + 16 * w, y + 12 * h, w, h, IntegralMat)
                neg1712 = self.getPixelValInIntegralMat(x + 17 * w, y + 12 * h, w, h, IntegralMat)
                neg1812 = self.getPixelValInIntegralMat(x + 18 * w, y + 12 * h, w, h, IntegralMat)
                neg1912 = self.getPixelValInIntegralMat(x + 19 * w, y + 12 * h, w, h, IntegralMat)
                neg013 = self.getPixelValInIntegralMat(x + 0 * w, y + 13 * h, w, h, IntegralMat)
                neg113 = self.getPixelValInIntegralMat(x + 1 * w, y + 13 * h, w, h, IntegralMat)
                neg213 = self.getPixelValInIntegralMat(x + 2 * w, y + 13 * h, w, h, IntegralMat)
                pos313 = self.getPixelValInIntegralMat(x + 3 * w, y + 13 * h, w, h, IntegralMat)
                pos413 = self.getPixelValInIntegralMat(x + 4 * w, y + 13 * h, w, h, IntegralMat)
                pos513 = self.getPixelValInIntegralMat(x + 5 * w, y + 13 * h, w, h, IntegralMat)
                pos613 = self.getPixelValInIntegralMat(x + 6 * w, y + 13 * h, w, h, IntegralMat)
                pos713 = self.getPixelValInIntegralMat(x + 7 * w, y + 13 * h, w, h, IntegralMat)
                pos813 = self.getPixelValInIntegralMat(x + 8 * w, y + 13 * h, w, h, IntegralMat)
                pos913 = self.getPixelValInIntegralMat(x + 9 * w, y + 13 * h, w, h, IntegralMat)
                pos1013 = self.getPixelValInIntegralMat(x + 10 * w, y + 13 * h, w, h, IntegralMat)
                pos1113 = self.getPixelValInIntegralMat(x + 11 * w, y + 13 * h, w, h, IntegralMat)
                pos1213 = self.getPixelValInIntegralMat(x + 12 * w, y + 13 * h, w, h, IntegralMat)
                pos1313 = self.getPixelValInIntegralMat(x + 13 * w, y + 13 * h, w, h, IntegralMat)
                neg1413 = self.getPixelValInIntegralMat(x + 14 * w, y + 13 * h, w, h, IntegralMat)
                neg1513 = self.getPixelValInIntegralMat(x + 15 * w, y + 13 * h, w, h, IntegralMat)
                neg1613 = self.getPixelValInIntegralMat(x + 16 * w, y + 13 * h, w, h, IntegralMat)
                neg1713 = self.getPixelValInIntegralMat(x + 17 * w, y + 13 * h, w, h, IntegralMat)
                neg1813 = self.getPixelValInIntegralMat(x + 18 * w, y + 13 * h, w, h, IntegralMat)
                neg1913 = self.getPixelValInIntegralMat(x + 19 * w, y + 13 * h, w, h, IntegralMat)
                neg014 = self.getPixelValInIntegralMat(x + 0 * w, y + 14 * h, w, h, IntegralMat)
                neg114 = self.getPixelValInIntegralMat(x + 1 * w, y + 14 * h, w, h, IntegralMat)
                neg214 = self.getPixelValInIntegralMat(x + 2 * w, y + 14 * h, w, h, IntegralMat)
                pos314 = self.getPixelValInIntegralMat(x + 3 * w, y + 14 * h, w, h, IntegralMat)
                pos414 = self.getPixelValInIntegralMat(x + 4 * w, y + 14 * h, w, h, IntegralMat)
                pos514 = self.getPixelValInIntegralMat(x + 5 * w, y + 14 * h, w, h, IntegralMat)
                pos614 = self.getPixelValInIntegralMat(x + 6 * w, y + 14 * h, w, h, IntegralMat)
                pos714 = self.getPixelValInIntegralMat(x + 7 * w, y + 14 * h, w, h, IntegralMat)
                pos814 = self.getPixelValInIntegralMat(x + 8 * w, y + 14 * h, w, h, IntegralMat)
                pos914 = self.getPixelValInIntegralMat(x + 9 * w, y + 14 * h, w, h, IntegralMat)
                pos1014 = self.getPixelValInIntegralMat(x + 10 * w, y + 14 * h, w, h, IntegralMat)
                pos1114 = self.getPixelValInIntegralMat(x + 11 * w, y + 14 * h, w, h, IntegralMat)
                pos1214 = self.getPixelValInIntegralMat(x + 12 * w, y + 14 * h, w, h, IntegralMat)
                pos1314 = self.getPixelValInIntegralMat(x + 13 * w, y + 14 * h, w, h, IntegralMat)
                neg1414 = self.getPixelValInIntegralMat(x + 14 * w, y + 14 * h, w, h, IntegralMat)
                neg1514 = self.getPixelValInIntegralMat(x + 15 * w, y + 14 * h, w, h, IntegralMat)
                neg1614 = self.getPixelValInIntegralMat(x + 16 * w, y + 14 * h, w, h, IntegralMat)
                neg1714 = self.getPixelValInIntegralMat(x + 17 * w, y + 14 * h, w, h, IntegralMat)
                neg1814 = self.getPixelValInIntegralMat(x + 18 * w, y + 14 * h, w, h, IntegralMat)
                neg1914 = self.getPixelValInIntegralMat(x + 19 * w, y + 14 * h, w, h, IntegralMat)
                neg015 = self.getPixelValInIntegralMat(x + 0 * w, y + 15 * h, w, h, IntegralMat)
                neg115 = self.getPixelValInIntegralMat(x + 1 * w, y + 15 * h, w, h, IntegralMat)
                neg215 = self.getPixelValInIntegralMat(x + 2 * w, y + 15 * h, w, h, IntegralMat)
                pos315 = self.getPixelValInIntegralMat(x + 3 * w, y + 15 * h, w, h, IntegralMat)
                neg415 = self.getPixelValInIntegralMat(x + 4 * w, y + 15 * h, w, h, IntegralMat)
                pos515 = self.getPixelValInIntegralMat(x + 5 * w, y + 15 * h, w, h, IntegralMat)
                pos615 = self.getPixelValInIntegralMat(x + 6 * w, y + 15 * h, w, h, IntegralMat)
                pos715 = self.getPixelValInIntegralMat(x + 7 * w, y + 15 * h, w, h, IntegralMat)
                pos815 = self.getPixelValInIntegralMat(x + 8 * w, y + 15 * h, w, h, IntegralMat)
                pos915 = self.getPixelValInIntegralMat(x + 9 * w, y + 15 * h, w, h, IntegralMat)
                pos1015 = self.getPixelValInIntegralMat(x + 10 * w, y + 15 * h, w, h, IntegralMat)
                pos1115 = self.getPixelValInIntegralMat(x + 11 * w, y + 15 * h, w, h, IntegralMat)
                pos1215 = self.getPixelValInIntegralMat(x + 12 * w, y + 15 * h, w, h, IntegralMat)
                pos1315 = self.getPixelValInIntegralMat(x + 13 * w, y + 15 * h, w, h, IntegralMat)
                pos1415 = self.getPixelValInIntegralMat(x + 14 * w, y + 15 * h, w, h, IntegralMat)
                neg1515 = self.getPixelValInIntegralMat(x + 15 * w, y + 15 * h, w, h, IntegralMat)
                neg1615 = self.getPixelValInIntegralMat(x + 16 * w, y + 15 * h, w, h, IntegralMat)
                neg1715 = self.getPixelValInIntegralMat(x + 17 * w, y + 15 * h, w, h, IntegralMat)
                neg1815 = self.getPixelValInIntegralMat(x + 18 * w, y + 15 * h, w, h, IntegralMat)
                neg1915 = self.getPixelValInIntegralMat(x + 19 * w, y + 15 * h, w, h, IntegralMat)
                neg016 = self.getPixelValInIntegralMat(x + 0 * w, y + 16 * h, w, h, IntegralMat)
                neg116 = self.getPixelValInIntegralMat(x + 1 * w, y + 16 * h, w, h, IntegralMat)
                neg216 = self.getPixelValInIntegralMat(x + 2 * w, y + 16 * h, w, h, IntegralMat)
                neg316 = self.getPixelValInIntegralMat(x + 3 * w, y + 16 * h, w, h, IntegralMat)
                neg416 = self.getPixelValInIntegralMat(x + 4 * w, y + 16 * h, w, h, IntegralMat)
                pos516 = self.getPixelValInIntegralMat(x + 5 * w, y + 16 * h, w, h, IntegralMat)
                pos616 = self.getPixelValInIntegralMat(x + 6 * w, y + 16 * h, w, h, IntegralMat)
                neg716 = self.getPixelValInIntegralMat(x + 7 * w, y + 16 * h, w, h, IntegralMat)
                neg816 = self.getPixelValInIntegralMat(x + 8 * w, y + 16 * h, w, h, IntegralMat)
                pos916 = self.getPixelValInIntegralMat(x + 9 * w, y + 16 * h, w, h, IntegralMat)
                pos1016 = self.getPixelValInIntegralMat(x + 10 * w, y + 16 * h, w, h, IntegralMat)
                pos1116 = self.getPixelValInIntegralMat(x + 11 * w, y + 16 * h, w, h, IntegralMat)
                pos1216 = self.getPixelValInIntegralMat(x + 12 * w, y + 16 * h, w, h, IntegralMat)
                pos1316 = self.getPixelValInIntegralMat(x + 13 * w, y + 16 * h, w, h, IntegralMat)
                neg1416 = self.getPixelValInIntegralMat(x + 14 * w, y + 16 * h, w, h, IntegralMat)
                neg1516 = self.getPixelValInIntegralMat(x + 15 * w, y + 16 * h, w, h, IntegralMat)
                neg1616 = self.getPixelValInIntegralMat(x + 16 * w, y + 16 * h, w, h, IntegralMat)
                neg1716 = self.getPixelValInIntegralMat(x + 17 * w, y + 16 * h, w, h, IntegralMat)
                neg1816 = self.getPixelValInIntegralMat(x + 18 * w, y + 16 * h, w, h, IntegralMat)
                neg1916 = self.getPixelValInIntegralMat(x + 19 * w, y + 16 * h, w, h, IntegralMat)
                neg017 = self.getPixelValInIntegralMat(x + 0 * w, y + 17 * h, w, h, IntegralMat)
                neg117 = self.getPixelValInIntegralMat(x + 1 * w, y + 17 * h, w, h, IntegralMat)
                neg217 = self.getPixelValInIntegralMat(x + 2 * w, y + 17 * h, w, h, IntegralMat)
                neg317 = self.getPixelValInIntegralMat(x + 3 * w, y + 17 * h, w, h, IntegralMat)
                pos417 = self.getPixelValInIntegralMat(x + 4 * w, y + 17 * h, w, h, IntegralMat)
                pos517 = self.getPixelValInIntegralMat(x + 5 * w, y + 17 * h, w, h, IntegralMat)
                pos617 = self.getPixelValInIntegralMat(x + 6 * w, y + 17 * h, w, h, IntegralMat)
                neg717 = self.getPixelValInIntegralMat(x + 7 * w, y + 17 * h, w, h, IntegralMat)
                pos817 = self.getPixelValInIntegralMat(x + 8 * w, y + 17 * h, w, h, IntegralMat)
                pos917 = self.getPixelValInIntegralMat(x + 9 * w, y + 17 * h, w, h, IntegralMat)
                pos1017 = self.getPixelValInIntegralMat(x + 10 * w, y + 17 * h, w, h, IntegralMat)
                pos1117 = self.getPixelValInIntegralMat(x + 11 * w, y + 17 * h, w, h, IntegralMat)
                pos1217 = self.getPixelValInIntegralMat(x + 12 * w, y + 17 * h, w, h, IntegralMat)
                pos1317 = self.getPixelValInIntegralMat(x + 13 * w, y + 17 * h, w, h, IntegralMat)
                neg1417 = self.getPixelValInIntegralMat(x + 14 * w, y + 17 * h, w, h, IntegralMat)
                neg1517 = self.getPixelValInIntegralMat(x + 15 * w, y + 17 * h, w, h, IntegralMat)
                neg1617 = self.getPixelValInIntegralMat(x + 16 * w, y + 17 * h, w, h, IntegralMat)
                neg1717 = self.getPixelValInIntegralMat(x + 17 * w, y + 17 * h, w, h, IntegralMat)
                neg1817 = self.getPixelValInIntegralMat(x + 18 * w, y + 17 * h, w, h, IntegralMat)
                neg1917 = self.getPixelValInIntegralMat(x + 19 * w, y + 17 * h, w, h, IntegralMat)
                neg018 = self.getPixelValInIntegralMat(x + 0 * w, y + 18 * h, w, h, IntegralMat)
                neg118 = self.getPixelValInIntegralMat(x + 1 * w, y + 18 * h, w, h, IntegralMat)
                neg218 = self.getPixelValInIntegralMat(x + 2 * w, y + 18 * h, w, h, IntegralMat)
                pos318 = self.getPixelValInIntegralMat(x + 3 * w, y + 18 * h, w, h, IntegralMat)
                pos418 = self.getPixelValInIntegralMat(x + 4 * w, y + 18 * h, w, h, IntegralMat)
                pos518 = self.getPixelValInIntegralMat(x + 5 * w, y + 18 * h, w, h, IntegralMat)
                pos618 = self.getPixelValInIntegralMat(x + 6 * w, y + 18 * h, w, h, IntegralMat)
                pos718 = self.getPixelValInIntegralMat(x + 7 * w, y + 18 * h, w, h, IntegralMat)
                pos818 = self.getPixelValInIntegralMat(x + 8 * w, y + 18 * h, w, h, IntegralMat)
                pos918 = self.getPixelValInIntegralMat(x + 9 * w, y + 18 * h, w, h, IntegralMat)
                pos1018 = self.getPixelValInIntegralMat(x + 10 * w, y + 18 * h, w, h, IntegralMat)
                pos1118 = self.getPixelValInIntegralMat(x + 11 * w, y + 18 * h, w, h, IntegralMat)
                pos1218 = self.getPixelValInIntegralMat(x + 12 * w, y + 18 * h, w, h, IntegralMat)
                pos1318 = self.getPixelValInIntegralMat(x + 13 * w, y + 18 * h, w, h, IntegralMat)
                neg1418 = self.getPixelValInIntegralMat(x + 14 * w, y + 18 * h, w, h, IntegralMat)
                neg1518 = self.getPixelValInIntegralMat(x + 15 * w, y + 18 * h, w, h, IntegralMat)
                neg1618 = self.getPixelValInIntegralMat(x + 16 * w, y + 18 * h, w, h, IntegralMat)
                neg1718 = self.getPixelValInIntegralMat(x + 17 * w, y + 18 * h, w, h, IntegralMat)
                neg1818 = self.getPixelValInIntegralMat(x + 18 * w, y + 18 * h, w, h, IntegralMat)
                neg1918 = self.getPixelValInIntegralMat(x + 19 * w, y + 18 * h, w, h, IntegralMat)
                neg019 = self.getPixelValInIntegralMat(x + 0 * w, y + 19 * h, w, h, IntegralMat)
                neg119 = self.getPixelValInIntegralMat(x + 1 * w, y + 19 * h, w, h, IntegralMat)
                pos219 = self.getPixelValInIntegralMat(x + 2 * w, y + 19 * h, w, h, IntegralMat)
                pos319 = self.getPixelValInIntegralMat(x + 3 * w, y + 19 * h, w, h, IntegralMat)
                pos419 = self.getPixelValInIntegralMat(x + 4 * w, y + 19 * h, w, h, IntegralMat)
                pos519 = self.getPixelValInIntegralMat(x + 5 * w, y + 19 * h, w, h, IntegralMat)
                pos619 = self.getPixelValInIntegralMat(x + 6 * w, y + 19 * h, w, h, IntegralMat)
                pos719 = self.getPixelValInIntegralMat(x + 7 * w, y + 19 * h, w, h, IntegralMat)
                pos819 = self.getPixelValInIntegralMat(x + 8 * w, y + 19 * h, w, h, IntegralMat)
                pos919 = self.getPixelValInIntegralMat(x + 9 * w, y + 19 * h, w, h, IntegralMat)
                pos1019 = self.getPixelValInIntegralMat(x + 10 * w, y + 19 * h, w, h, IntegralMat)
                pos1119 = self.getPixelValInIntegralMat(x + 11 * w, y + 19 * h, w, h, IntegralMat)
                pos1219 = self.getPixelValInIntegralMat(x + 12 * w, y + 19 * h, w, h, IntegralMat)
                pos1319 = self.getPixelValInIntegralMat(x + 13 * w, y + 19 * h, w, h, IntegralMat)
                neg1419 = self.getPixelValInIntegralMat(x + 14 * w, y + 19 * h, w, h, IntegralMat)
                neg1519 = self.getPixelValInIntegralMat(x + 15 * w, y + 19 * h, w, h, IntegralMat)
                neg1619 = self.getPixelValInIntegralMat(x + 16 * w, y + 19 * h, w, h, IntegralMat)
                neg1719 = self.getPixelValInIntegralMat(x + 17 * w, y + 19 * h, w, h, IntegralMat)
                neg1819 = self.getPixelValInIntegralMat(x + 18 * w, y + 19 * h, w, h, IntegralMat)
                neg1919 = self.getPixelValInIntegralMat(x + 19 * w, y + 19 * h, w, h, IntegralMat)
                neg020 = self.getPixelValInIntegralMat(x + 0 * w, y + 20 * h, w, h, IntegralMat)
                neg120 = self.getPixelValInIntegralMat(x + 1 * w, y + 20 * h, w, h, IntegralMat)
                pos220 = self.getPixelValInIntegralMat(x + 2 * w, y + 20 * h, w, h, IntegralMat)
                pos320 = self.getPixelValInIntegralMat(x + 3 * w, y + 20 * h, w, h, IntegralMat)
                pos420 = self.getPixelValInIntegralMat(x + 4 * w, y + 20 * h, w, h, IntegralMat)
                pos520 = self.getPixelValInIntegralMat(x + 5 * w, y + 20 * h, w, h, IntegralMat)
                pos620 = self.getPixelValInIntegralMat(x + 6 * w, y + 20 * h, w, h, IntegralMat)
                pos720 = self.getPixelValInIntegralMat(x + 7 * w, y + 20 * h, w, h, IntegralMat)
                pos820 = self.getPixelValInIntegralMat(x + 8 * w, y + 20 * h, w, h, IntegralMat)
                pos920 = self.getPixelValInIntegralMat(x + 9 * w, y + 20 * h, w, h, IntegralMat)
                pos1020 = self.getPixelValInIntegralMat(x + 10 * w, y + 20 * h, w, h, IntegralMat)
                pos1120 = self.getPixelValInIntegralMat(x + 11 * w, y + 20 * h, w, h, IntegralMat)
                pos1220 = self.getPixelValInIntegralMat(x + 12 * w, y + 20 * h, w, h, IntegralMat)
                neg1320 = self.getPixelValInIntegralMat(x + 13 * w, y + 20 * h, w, h, IntegralMat)
                neg1420 = self.getPixelValInIntegralMat(x + 14 * w, y + 20 * h, w, h, IntegralMat)
                neg1520 = self.getPixelValInIntegralMat(x + 15 * w, y + 20 * h, w, h, IntegralMat)
                neg1620 = self.getPixelValInIntegralMat(x + 16 * w, y + 20 * h, w, h, IntegralMat)
                neg1720 = self.getPixelValInIntegralMat(x + 17 * w, y + 20 * h, w, h, IntegralMat)
                neg1820 = self.getPixelValInIntegralMat(x + 18 * w, y + 20 * h, w, h, IntegralMat)
                neg1920 = self.getPixelValInIntegralMat(x + 19 * w, y + 20 * h, w, h, IntegralMat)
                neg021 = self.getPixelValInIntegralMat(x + 0 * w, y + 21 * h, w, h, IntegralMat)
                neg121 = self.getPixelValInIntegralMat(x + 1 * w, y + 21 * h, w, h, IntegralMat)
                pos221 = self.getPixelValInIntegralMat(x + 2 * w, y + 21 * h, w, h, IntegralMat)
                pos321 = self.getPixelValInIntegralMat(x + 3 * w, y + 21 * h, w, h, IntegralMat)
                pos421 = self.getPixelValInIntegralMat(x + 4 * w, y + 21 * h, w, h, IntegralMat)
                pos521 = self.getPixelValInIntegralMat(x + 5 * w, y + 21 * h, w, h, IntegralMat)
                pos621 = self.getPixelValInIntegralMat(x + 6 * w, y + 21 * h, w, h, IntegralMat)
                pos721 = self.getPixelValInIntegralMat(x + 7 * w, y + 21 * h, w, h, IntegralMat)
                pos821 = self.getPixelValInIntegralMat(x + 8 * w, y + 21 * h, w, h, IntegralMat)
                pos921 = self.getPixelValInIntegralMat(x + 9 * w, y + 21 * h, w, h, IntegralMat)
                pos1021 = self.getPixelValInIntegralMat(x + 10 * w, y + 21 * h, w, h, IntegralMat)
                pos1121 = self.getPixelValInIntegralMat(x + 11 * w, y + 21 * h, w, h, IntegralMat)
                pos1221 = self.getPixelValInIntegralMat(x + 12 * w, y + 21 * h, w, h, IntegralMat)
                neg1321 = self.getPixelValInIntegralMat(x + 13 * w, y + 21 * h, w, h, IntegralMat)
                neg1421 = self.getPixelValInIntegralMat(x + 14 * w, y + 21 * h, w, h, IntegralMat)
                neg1521 = self.getPixelValInIntegralMat(x + 15 * w, y + 21 * h, w, h, IntegralMat)
                neg1621 = self.getPixelValInIntegralMat(x + 16 * w, y + 21 * h, w, h, IntegralMat)
                neg1721 = self.getPixelValInIntegralMat(x + 17 * w, y + 21 * h, w, h, IntegralMat)
                neg1821 = self.getPixelValInIntegralMat(x + 18 * w, y + 21 * h, w, h, IntegralMat)
                neg1921 = self.getPixelValInIntegralMat(x + 19 * w, y + 21 * h, w, h, IntegralMat)
                neg022 = self.getPixelValInIntegralMat(x + 0 * w, y + 22 * h, w, h, IntegralMat)
                pos122 = self.getPixelValInIntegralMat(x + 1 * w, y + 22 * h, w, h, IntegralMat)
                pos222 = self.getPixelValInIntegralMat(x + 2 * w, y + 22 * h, w, h, IntegralMat)
                pos322 = self.getPixelValInIntegralMat(x + 3 * w, y + 22 * h, w, h, IntegralMat)
                pos422 = self.getPixelValInIntegralMat(x + 4 * w, y + 22 * h, w, h, IntegralMat)
                pos522 = self.getPixelValInIntegralMat(x + 5 * w, y + 22 * h, w, h, IntegralMat)
                pos622 = self.getPixelValInIntegralMat(x + 6 * w, y + 22 * h, w, h, IntegralMat)
                pos722 = self.getPixelValInIntegralMat(x + 7 * w, y + 22 * h, w, h, IntegralMat)
                pos822 = self.getPixelValInIntegralMat(x + 8 * w, y + 22 * h, w, h, IntegralMat)
                pos922 = self.getPixelValInIntegralMat(x + 9 * w, y + 22 * h, w, h, IntegralMat)
                pos1022 = self.getPixelValInIntegralMat(x + 10 * w, y + 22 * h, w, h, IntegralMat)
                pos1122 = self.getPixelValInIntegralMat(x + 11 * w, y + 22 * h, w, h, IntegralMat)
                pos1222 = self.getPixelValInIntegralMat(x + 12 * w, y + 22 * h, w, h, IntegralMat)
                neg1322 = self.getPixelValInIntegralMat(x + 13 * w, y + 22 * h, w, h, IntegralMat)
                neg1422 = self.getPixelValInIntegralMat(x + 14 * w, y + 22 * h, w, h, IntegralMat)
                neg1522 = self.getPixelValInIntegralMat(x + 15 * w, y + 22 * h, w, h, IntegralMat)
                neg1622 = self.getPixelValInIntegralMat(x + 16 * w, y + 22 * h, w, h, IntegralMat)
                neg1722 = self.getPixelValInIntegralMat(x + 17 * w, y + 22 * h, w, h, IntegralMat)
                neg1822 = self.getPixelValInIntegralMat(x + 18 * w, y + 22 * h, w, h, IntegralMat)
                neg1922 = self.getPixelValInIntegralMat(x + 19 * w, y + 22 * h, w, h, IntegralMat)
                neg023 = self.getPixelValInIntegralMat(x + 0 * w, y + 23 * h, w, h, IntegralMat)
                pos123 = self.getPixelValInIntegralMat(x + 1 * w, y + 23 * h, w, h, IntegralMat)
                pos223 = self.getPixelValInIntegralMat(x + 2 * w, y + 23 * h, w, h, IntegralMat)
                pos323 = self.getPixelValInIntegralMat(x + 3 * w, y + 23 * h, w, h, IntegralMat)
                pos423 = self.getPixelValInIntegralMat(x + 4 * w, y + 23 * h, w, h, IntegralMat)
                pos523 = self.getPixelValInIntegralMat(x + 5 * w, y + 23 * h, w, h, IntegralMat)
                pos623 = self.getPixelValInIntegralMat(x + 6 * w, y + 23 * h, w, h, IntegralMat)
                pos723 = self.getPixelValInIntegralMat(x + 7 * w, y + 23 * h, w, h, IntegralMat)
                pos823 = self.getPixelValInIntegralMat(x + 8 * w, y + 23 * h, w, h, IntegralMat)
                pos923 = self.getPixelValInIntegralMat(x + 9 * w, y + 23 * h, w, h, IntegralMat)
                pos1023 = self.getPixelValInIntegralMat(x + 10 * w, y + 23 * h, w, h, IntegralMat)
                pos1123 = self.getPixelValInIntegralMat(x + 11 * w, y + 23 * h, w, h, IntegralMat)
                pos1223 = self.getPixelValInIntegralMat(x + 12 * w, y + 23 * h, w, h, IntegralMat)
                pos1323 = self.getPixelValInIntegralMat(x + 13 * w, y + 23 * h, w, h, IntegralMat)
                neg1423 = self.getPixelValInIntegralMat(x + 14 * w, y + 23 * h, w, h, IntegralMat)
                neg1523 = self.getPixelValInIntegralMat(x + 15 * w, y + 23 * h, w, h, IntegralMat)
                neg1623 = self.getPixelValInIntegralMat(x + 16 * w, y + 23 * h, w, h, IntegralMat)
                neg1723 = self.getPixelValInIntegralMat(x + 17 * w, y + 23 * h, w, h, IntegralMat)
                neg1823 = self.getPixelValInIntegralMat(x + 18 * w, y + 23 * h, w, h, IntegralMat)
                neg1923 = self.getPixelValInIntegralMat(x + 19 * w, y + 23 * h, w, h, IntegralMat)
                neg024 = self.getPixelValInIntegralMat(x + 0 * w, y + 24 * h, w, h, IntegralMat)
                pos124 = self.getPixelValInIntegralMat(x + 1 * w, y + 24 * h, w, h, IntegralMat)
                neg224 = self.getPixelValInIntegralMat(x + 2 * w, y + 24 * h, w, h, IntegralMat)
                neg324 = self.getPixelValInIntegralMat(x + 3 * w, y + 24 * h, w, h, IntegralMat)
                pos424 = self.getPixelValInIntegralMat(x + 4 * w, y + 24 * h, w, h, IntegralMat)
                pos524 = self.getPixelValInIntegralMat(x + 5 * w, y + 24 * h, w, h, IntegralMat)
                pos624 = self.getPixelValInIntegralMat(x + 6 * w, y + 24 * h, w, h, IntegralMat)
                pos724 = self.getPixelValInIntegralMat(x + 7 * w, y + 24 * h, w, h, IntegralMat)
                pos824 = self.getPixelValInIntegralMat(x + 8 * w, y + 24 * h, w, h, IntegralMat)
                pos924 = self.getPixelValInIntegralMat(x + 9 * w, y + 24 * h, w, h, IntegralMat)
                pos1024 = self.getPixelValInIntegralMat(x + 10 * w, y + 24 * h, w, h, IntegralMat)
                pos1124 = self.getPixelValInIntegralMat(x + 11 * w, y + 24 * h, w, h, IntegralMat)
                pos1224 = self.getPixelValInIntegralMat(x + 12 * w, y + 24 * h, w, h, IntegralMat)
                pos1324 = self.getPixelValInIntegralMat(x + 13 * w, y + 24 * h, w, h, IntegralMat)
                neg1424 = self.getPixelValInIntegralMat(x + 14 * w, y + 24 * h, w, h, IntegralMat)
                neg1524 = self.getPixelValInIntegralMat(x + 15 * w, y + 24 * h, w, h, IntegralMat)
                neg1624 = self.getPixelValInIntegralMat(x + 16 * w, y + 24 * h, w, h, IntegralMat)
                neg1724 = self.getPixelValInIntegralMat(x + 17 * w, y + 24 * h, w, h, IntegralMat)
                neg1824 = self.getPixelValInIntegralMat(x + 18 * w, y + 24 * h, w, h, IntegralMat)
                neg1924 = self.getPixelValInIntegralMat(x + 19 * w, y + 24 * h, w, h, IntegralMat)
                neg025 = self.getPixelValInIntegralMat(x + 0 * w, y + 25 * h, w, h, IntegralMat)
                neg125 = self.getPixelValInIntegralMat(x + 1 * w, y + 25 * h, w, h, IntegralMat)
                neg225 = self.getPixelValInIntegralMat(x + 2 * w, y + 25 * h, w, h, IntegralMat)
                neg325 = self.getPixelValInIntegralMat(x + 3 * w, y + 25 * h, w, h, IntegralMat)
                neg425 = self.getPixelValInIntegralMat(x + 4 * w, y + 25 * h, w, h, IntegralMat)
                pos525 = self.getPixelValInIntegralMat(x + 5 * w, y + 25 * h, w, h, IntegralMat)
                pos625 = self.getPixelValInIntegralMat(x + 6 * w, y + 25 * h, w, h, IntegralMat)
                pos725 = self.getPixelValInIntegralMat(x + 7 * w, y + 25 * h, w, h, IntegralMat)
                pos825 = self.getPixelValInIntegralMat(x + 8 * w, y + 25 * h, w, h, IntegralMat)
                pos925 = self.getPixelValInIntegralMat(x + 9 * w, y + 25 * h, w, h, IntegralMat)
                pos1025 = self.getPixelValInIntegralMat(x + 10 * w, y + 25 * h, w, h, IntegralMat)
                pos1125 = self.getPixelValInIntegralMat(x + 11 * w, y + 25 * h, w, h, IntegralMat)
                pos1225 = self.getPixelValInIntegralMat(x + 12 * w, y + 25 * h, w, h, IntegralMat)
                pos1325 = self.getPixelValInIntegralMat(x + 13 * w, y + 25 * h, w, h, IntegralMat)
                pos1425 = self.getPixelValInIntegralMat(x + 14 * w, y + 25 * h, w, h, IntegralMat)
                neg1525 = self.getPixelValInIntegralMat(x + 15 * w, y + 25 * h, w, h, IntegralMat)
                neg1625 = self.getPixelValInIntegralMat(x + 16 * w, y + 25 * h, w, h, IntegralMat)
                neg1725 = self.getPixelValInIntegralMat(x + 17 * w, y + 25 * h, w, h, IntegralMat)
                neg1825 = self.getPixelValInIntegralMat(x + 18 * w, y + 25 * h, w, h, IntegralMat)
                neg1925 = self.getPixelValInIntegralMat(x + 19 * w, y + 25 * h, w, h, IntegralMat)
                neg026 = self.getPixelValInIntegralMat(x + 0 * w, y + 26 * h, w, h, IntegralMat)
                neg126 = self.getPixelValInIntegralMat(x + 1 * w, y + 26 * h, w, h, IntegralMat)
                neg226 = self.getPixelValInIntegralMat(x + 2 * w, y + 26 * h, w, h, IntegralMat)
                neg326 = self.getPixelValInIntegralMat(x + 3 * w, y + 26 * h, w, h, IntegralMat)
                neg426 = self.getPixelValInIntegralMat(x + 4 * w, y + 26 * h, w, h, IntegralMat)
                pos526 = self.getPixelValInIntegralMat(x + 5 * w, y + 26 * h, w, h, IntegralMat)
                pos626 = self.getPixelValInIntegralMat(x + 6 * w, y + 26 * h, w, h, IntegralMat)
                pos726 = self.getPixelValInIntegralMat(x + 7 * w, y + 26 * h, w, h, IntegralMat)
                pos826 = self.getPixelValInIntegralMat(x + 8 * w, y + 26 * h, w, h, IntegralMat)
                pos926 = self.getPixelValInIntegralMat(x + 9 * w, y + 26 * h, w, h, IntegralMat)
                pos1026 = self.getPixelValInIntegralMat(x + 10 * w, y + 26 * h, w, h, IntegralMat)
                pos1126 = self.getPixelValInIntegralMat(x + 11 * w, y + 26 * h, w, h, IntegralMat)
                pos1226 = self.getPixelValInIntegralMat(x + 12 * w, y + 26 * h, w, h, IntegralMat)
                pos1326 = self.getPixelValInIntegralMat(x + 13 * w, y + 26 * h, w, h, IntegralMat)
                pos1426 = self.getPixelValInIntegralMat(x + 14 * w, y + 26 * h, w, h, IntegralMat)
                pos1526 = self.getPixelValInIntegralMat(x + 15 * w, y + 26 * h, w, h, IntegralMat)
                neg1626 = self.getPixelValInIntegralMat(x + 16 * w, y + 26 * h, w, h, IntegralMat)
                neg1726 = self.getPixelValInIntegralMat(x + 17 * w, y + 26 * h, w, h, IntegralMat)
                neg1826 = self.getPixelValInIntegralMat(x + 18 * w, y + 26 * h, w, h, IntegralMat)
                neg1926 = self.getPixelValInIntegralMat(x + 19 * w, y + 26 * h, w, h, IntegralMat)
                neg027 = self.getPixelValInIntegralMat(x + 0 * w, y + 27 * h, w, h, IntegralMat)
                neg127 = self.getPixelValInIntegralMat(x + 1 * w, y + 27 * h, w, h, IntegralMat)
                neg227 = self.getPixelValInIntegralMat(x + 2 * w, y + 27 * h, w, h, IntegralMat)
                neg327 = self.getPixelValInIntegralMat(x + 3 * w, y + 27 * h, w, h, IntegralMat)
                neg427 = self.getPixelValInIntegralMat(x + 4 * w, y + 27 * h, w, h, IntegralMat)
                pos527 = self.getPixelValInIntegralMat(x + 5 * w, y + 27 * h, w, h, IntegralMat)
                pos627 = self.getPixelValInIntegralMat(x + 6 * w, y + 27 * h, w, h, IntegralMat)
                pos727 = self.getPixelValInIntegralMat(x + 7 * w, y + 27 * h, w, h, IntegralMat)
                pos827 = self.getPixelValInIntegralMat(x + 8 * w, y + 27 * h, w, h, IntegralMat)
                pos927 = self.getPixelValInIntegralMat(x + 9 * w, y + 27 * h, w, h, IntegralMat)
                pos1027 = self.getPixelValInIntegralMat(x + 10 * w, y + 27 * h, w, h, IntegralMat)
                pos1127 = self.getPixelValInIntegralMat(x + 11 * w, y + 27 * h, w, h, IntegralMat)
                pos1227 = self.getPixelValInIntegralMat(x + 12 * w, y + 27 * h, w, h, IntegralMat)
                pos1327 = self.getPixelValInIntegralMat(x + 13 * w, y + 27 * h, w, h, IntegralMat)
                pos1427 = self.getPixelValInIntegralMat(x + 14 * w, y + 27 * h, w, h, IntegralMat)
                pos1527 = self.getPixelValInIntegralMat(x + 15 * w, y + 27 * h, w, h, IntegralMat)
                pos1627 = self.getPixelValInIntegralMat(x + 16 * w, y + 27 * h, w, h, IntegralMat)
                neg1727 = self.getPixelValInIntegralMat(x + 17 * w, y + 27 * h, w, h, IntegralMat)
                neg1827 = self.getPixelValInIntegralMat(x + 18 * w, y + 27 * h, w, h, IntegralMat)
                neg1927 = self.getPixelValInIntegralMat(x + 19 * w, y + 27 * h, w, h, IntegralMat)
                neg028 = self.getPixelValInIntegralMat(x + 0 * w, y + 28 * h, w, h, IntegralMat)
                neg128 = self.getPixelValInIntegralMat(x + 1 * w, y + 28 * h, w, h, IntegralMat)
                neg228 = self.getPixelValInIntegralMat(x + 2 * w, y + 28 * h, w, h, IntegralMat)
                neg328 = self.getPixelValInIntegralMat(x + 3 * w, y + 28 * h, w, h, IntegralMat)
                neg428 = self.getPixelValInIntegralMat(x + 4 * w, y + 28 * h, w, h, IntegralMat)
                pos528 = self.getPixelValInIntegralMat(x + 5 * w, y + 28 * h, w, h, IntegralMat)
                pos628 = self.getPixelValInIntegralMat(x + 6 * w, y + 28 * h, w, h, IntegralMat)
                pos728 = self.getPixelValInIntegralMat(x + 7 * w, y + 28 * h, w, h, IntegralMat)
                pos828 = self.getPixelValInIntegralMat(x + 8 * w, y + 28 * h, w, h, IntegralMat)
                neg928 = self.getPixelValInIntegralMat(x + 9 * w, y + 28 * h, w, h, IntegralMat)
                neg1028 = self.getPixelValInIntegralMat(x + 10 * w, y + 28 * h, w, h, IntegralMat)
                neg1128 = self.getPixelValInIntegralMat(x + 11 * w, y + 28 * h, w, h, IntegralMat)
                pos1228 = self.getPixelValInIntegralMat(x + 12 * w, y + 28 * h, w, h, IntegralMat)
                pos1328 = self.getPixelValInIntegralMat(x + 13 * w, y + 28 * h, w, h, IntegralMat)
                pos1428 = self.getPixelValInIntegralMat(x + 14 * w, y + 28 * h, w, h, IntegralMat)
                pos1528 = self.getPixelValInIntegralMat(x + 15 * w, y + 28 * h, w, h, IntegralMat)
                pos1628 = self.getPixelValInIntegralMat(x + 16 * w, y + 28 * h, w, h, IntegralMat)
                neg1728 = self.getPixelValInIntegralMat(x + 17 * w, y + 28 * h, w, h, IntegralMat)
                neg1828 = self.getPixelValInIntegralMat(x + 18 * w, y + 28 * h, w, h, IntegralMat)
                neg1928 = self.getPixelValInIntegralMat(x + 19 * w, y + 28 * h, w, h, IntegralMat)
                neg029 = self.getPixelValInIntegralMat(x + 0 * w, y + 29 * h, w, h, IntegralMat)
                neg129 = self.getPixelValInIntegralMat(x + 1 * w, y + 29 * h, w, h, IntegralMat)
                neg229 = self.getPixelValInIntegralMat(x + 2 * w, y + 29 * h, w, h, IntegralMat)
                neg329 = self.getPixelValInIntegralMat(x + 3 * w, y + 29 * h, w, h, IntegralMat)
                pos429 = self.getPixelValInIntegralMat(x + 4 * w, y + 29 * h, w, h, IntegralMat)
                pos529 = self.getPixelValInIntegralMat(x + 5 * w, y + 29 * h, w, h, IntegralMat)
                pos629 = self.getPixelValInIntegralMat(x + 6 * w, y + 29 * h, w, h, IntegralMat)
                pos729 = self.getPixelValInIntegralMat(x + 7 * w, y + 29 * h, w, h, IntegralMat)
                neg829 = self.getPixelValInIntegralMat(x + 8 * w, y + 29 * h, w, h, IntegralMat)
                neg929 = self.getPixelValInIntegralMat(x + 9 * w, y + 29 * h, w, h, IntegralMat)
                neg1029 = self.getPixelValInIntegralMat(x + 10 * w, y + 29 * h, w, h, IntegralMat)
                neg1129 = self.getPixelValInIntegralMat(x + 11 * w, y + 29 * h, w, h, IntegralMat)
                pos1229 = self.getPixelValInIntegralMat(x + 12 * w, y + 29 * h, w, h, IntegralMat)
                pos1329 = self.getPixelValInIntegralMat(x + 13 * w, y + 29 * h, w, h, IntegralMat)
                pos1429 = self.getPixelValInIntegralMat(x + 14 * w, y + 29 * h, w, h, IntegralMat)
                pos1529 = self.getPixelValInIntegralMat(x + 15 * w, y + 29 * h, w, h, IntegralMat)
                pos1629 = self.getPixelValInIntegralMat(x + 16 * w, y + 29 * h, w, h, IntegralMat)
                pos1729 = self.getPixelValInIntegralMat(x + 17 * w, y + 29 * h, w, h, IntegralMat)
                neg1829 = self.getPixelValInIntegralMat(x + 18 * w, y + 29 * h, w, h, IntegralMat)
                neg1929 = self.getPixelValInIntegralMat(x + 19 * w, y + 29 * h, w, h, IntegralMat)
                neg030 = self.getPixelValInIntegralMat(x + 0 * w, y + 30 * h, w, h, IntegralMat)
                neg130 = self.getPixelValInIntegralMat(x + 1 * w, y + 30 * h, w, h, IntegralMat)
                neg230 = self.getPixelValInIntegralMat(x + 2 * w, y + 30 * h, w, h, IntegralMat)
                neg330 = self.getPixelValInIntegralMat(x + 3 * w, y + 30 * h, w, h, IntegralMat)
                pos430 = self.getPixelValInIntegralMat(x + 4 * w, y + 30 * h, w, h, IntegralMat)
                pos530 = self.getPixelValInIntegralMat(x + 5 * w, y + 30 * h, w, h, IntegralMat)
                pos630 = self.getPixelValInIntegralMat(x + 6 * w, y + 30 * h, w, h, IntegralMat)
                neg730 = self.getPixelValInIntegralMat(x + 7 * w, y + 30 * h, w, h, IntegralMat)
                neg830 = self.getPixelValInIntegralMat(x + 8 * w, y + 30 * h, w, h, IntegralMat)
                neg930 = self.getPixelValInIntegralMat(x + 9 * w, y + 30 * h, w, h, IntegralMat)
                neg1030 = self.getPixelValInIntegralMat(x + 10 * w, y + 30 * h, w, h, IntegralMat)
                neg1130 = self.getPixelValInIntegralMat(x + 11 * w, y + 30 * h, w, h, IntegralMat)
                neg1230 = self.getPixelValInIntegralMat(x + 12 * w, y + 30 * h, w, h, IntegralMat)
                neg1330 = self.getPixelValInIntegralMat(x + 13 * w, y + 30 * h, w, h, IntegralMat)
                pos1430 = self.getPixelValInIntegralMat(x + 14 * w, y + 30 * h, w, h, IntegralMat)
                pos1530 = self.getPixelValInIntegralMat(x + 15 * w, y + 30 * h, w, h, IntegralMat)
                pos1630 = self.getPixelValInIntegralMat(x + 16 * w, y + 30 * h, w, h, IntegralMat)
                pos1730 = self.getPixelValInIntegralMat(x + 17 * w, y + 30 * h, w, h, IntegralMat)
                neg1830 = self.getPixelValInIntegralMat(x + 18 * w, y + 30 * h, w, h, IntegralMat)
                neg1930 = self.getPixelValInIntegralMat(x + 19 * w, y + 30 * h, w, h, IntegralMat)
                neg031 = self.getPixelValInIntegralMat(x + 0 * w, y + 31 * h, w, h, IntegralMat)
                neg131 = self.getPixelValInIntegralMat(x + 1 * w, y + 31 * h, w, h, IntegralMat)
                neg231 = self.getPixelValInIntegralMat(x + 2 * w, y + 31 * h, w, h, IntegralMat)
                pos331 = self.getPixelValInIntegralMat(x + 3 * w, y + 31 * h, w, h, IntegralMat)
                pos431 = self.getPixelValInIntegralMat(x + 4 * w, y + 31 * h, w, h, IntegralMat)
                neg531 = self.getPixelValInIntegralMat(x + 5 * w, y + 31 * h, w, h, IntegralMat)
                neg631 = self.getPixelValInIntegralMat(x + 6 * w, y + 31 * h, w, h, IntegralMat)
                neg731 = self.getPixelValInIntegralMat(x + 7 * w, y + 31 * h, w, h, IntegralMat)
                neg831 = self.getPixelValInIntegralMat(x + 8 * w, y + 31 * h, w, h, IntegralMat)
                neg931 = self.getPixelValInIntegralMat(x + 9 * w, y + 31 * h, w, h, IntegralMat)
                neg1031 = self.getPixelValInIntegralMat(x + 10 * w, y + 31 * h, w, h, IntegralMat)
                neg1131 = self.getPixelValInIntegralMat(x + 11 * w, y + 31 * h, w, h, IntegralMat)
                neg1231 = self.getPixelValInIntegralMat(x + 12 * w, y + 31 * h, w, h, IntegralMat)
                neg1331 = self.getPixelValInIntegralMat(x + 13 * w, y + 31 * h, w, h, IntegralMat)
                neg1431 = self.getPixelValInIntegralMat(x + 14 * w, y + 31 * h, w, h, IntegralMat)
                pos1531 = self.getPixelValInIntegralMat(x + 15 * w, y + 31 * h, w, h, IntegralMat)
                pos1631 = self.getPixelValInIntegralMat(x + 16 * w, y + 31 * h, w, h, IntegralMat)
                pos1731 = self.getPixelValInIntegralMat(x + 17 * w, y + 31 * h, w, h, IntegralMat)
                neg1831 = self.getPixelValInIntegralMat(x + 18 * w, y + 31 * h, w, h, IntegralMat)
                neg1931 = self.getPixelValInIntegralMat(x + 19 * w, y + 31 * h, w, h, IntegralMat)
                neg032 = self.getPixelValInIntegralMat(x + 0 * w, y + 32 * h, w, h, IntegralMat)
                neg132 = self.getPixelValInIntegralMat(x + 1 * w, y + 32 * h, w, h, IntegralMat)
                neg232 = self.getPixelValInIntegralMat(x + 2 * w, y + 32 * h, w, h, IntegralMat)
                pos332 = self.getPixelValInIntegralMat(x + 3 * w, y + 32 * h, w, h, IntegralMat)
                pos432 = self.getPixelValInIntegralMat(x + 4 * w, y + 32 * h, w, h, IntegralMat)
                neg532 = self.getPixelValInIntegralMat(x + 5 * w, y + 32 * h, w, h, IntegralMat)
                neg632 = self.getPixelValInIntegralMat(x + 6 * w, y + 32 * h, w, h, IntegralMat)
                neg732 = self.getPixelValInIntegralMat(x + 7 * w, y + 32 * h, w, h, IntegralMat)
                neg832 = self.getPixelValInIntegralMat(x + 8 * w, y + 32 * h, w, h, IntegralMat)
                neg932 = self.getPixelValInIntegralMat(x + 9 * w, y + 32 * h, w, h, IntegralMat)
                neg1032 = self.getPixelValInIntegralMat(x + 10 * w, y + 32 * h, w, h, IntegralMat)
                neg1132 = self.getPixelValInIntegralMat(x + 11 * w, y + 32 * h, w, h, IntegralMat)
                neg1232 = self.getPixelValInIntegralMat(x + 12 * w, y + 32 * h, w, h, IntegralMat)
                neg1332 = self.getPixelValInIntegralMat(x + 13 * w, y + 32 * h, w, h, IntegralMat)
                neg1432 = self.getPixelValInIntegralMat(x + 14 * w, y + 32 * h, w, h, IntegralMat)
                pos1532 = self.getPixelValInIntegralMat(x + 15 * w, y + 32 * h, w, h, IntegralMat)
                pos1632 = self.getPixelValInIntegralMat(x + 16 * w, y + 32 * h, w, h, IntegralMat)
                pos1732 = self.getPixelValInIntegralMat(x + 17 * w, y + 32 * h, w, h, IntegralMat)
                neg1832 = self.getPixelValInIntegralMat(x + 18 * w, y + 32 * h, w, h, IntegralMat)
                neg1932 = self.getPixelValInIntegralMat(x + 19 * w, y + 32 * h, w, h, IntegralMat)
                neg033 = self.getPixelValInIntegralMat(x + 0 * w, y + 33 * h, w, h, IntegralMat)
                neg133 = self.getPixelValInIntegralMat(x + 1 * w, y + 33 * h, w, h, IntegralMat)
                neg233 = self.getPixelValInIntegralMat(x + 2 * w, y + 33 * h, w, h, IntegralMat)
                neg333 = self.getPixelValInIntegralMat(x + 3 * w, y + 33 * h, w, h, IntegralMat)
                neg433 = self.getPixelValInIntegralMat(x + 4 * w, y + 33 * h, w, h, IntegralMat)
                neg533 = self.getPixelValInIntegralMat(x + 5 * w, y + 33 * h, w, h, IntegralMat)
                neg633 = self.getPixelValInIntegralMat(x + 6 * w, y + 33 * h, w, h, IntegralMat)
                neg733 = self.getPixelValInIntegralMat(x + 7 * w, y + 33 * h, w, h, IntegralMat)
                neg833 = self.getPixelValInIntegralMat(x + 8 * w, y + 33 * h, w, h, IntegralMat)
                neg933 = self.getPixelValInIntegralMat(x + 9 * w, y + 33 * h, w, h, IntegralMat)
                neg1033 = self.getPixelValInIntegralMat(x + 10 * w, y + 33 * h, w, h, IntegralMat)
                neg1133 = self.getPixelValInIntegralMat(x + 11 * w, y + 33 * h, w, h, IntegralMat)
                neg1233 = self.getPixelValInIntegralMat(x + 12 * w, y + 33 * h, w, h, IntegralMat)
                neg1333 = self.getPixelValInIntegralMat(x + 13 * w, y + 33 * h, w, h, IntegralMat)
                neg1433 = self.getPixelValInIntegralMat(x + 14 * w, y + 33 * h, w, h, IntegralMat)
                neg1533 = self.getPixelValInIntegralMat(x + 15 * w, y + 33 * h, w, h, IntegralMat)
                neg1633 = self.getPixelValInIntegralMat(x + 16 * w, y + 33 * h, w, h, IntegralMat)
                pos1733 = self.getPixelValInIntegralMat(x + 17 * w, y + 33 * h, w, h, IntegralMat)
                neg1833 = self.getPixelValInIntegralMat(x + 18 * w, y + 33 * h, w, h, IntegralMat)
                neg1933 = self.getPixelValInIntegralMat(x + 19 * w, y + 33 * h, w, h, IntegralMat)
                neg034 = self.getPixelValInIntegralMat(x + 0 * w, y + 34 * h, w, h, IntegralMat)
                neg134 = self.getPixelValInIntegralMat(x + 1 * w, y + 34 * h, w, h, IntegralMat)
                neg234 = self.getPixelValInIntegralMat(x + 2 * w, y + 34 * h, w, h, IntegralMat)
                neg334 = self.getPixelValInIntegralMat(x + 3 * w, y + 34 * h, w, h, IntegralMat)
                neg434 = self.getPixelValInIntegralMat(x + 4 * w, y + 34 * h, w, h, IntegralMat)
                neg534 = self.getPixelValInIntegralMat(x + 5 * w, y + 34 * h, w, h, IntegralMat)
                neg634 = self.getPixelValInIntegralMat(x + 6 * w, y + 34 * h, w, h, IntegralMat)
                neg734 = self.getPixelValInIntegralMat(x + 7 * w, y + 34 * h, w, h, IntegralMat)
                neg834 = self.getPixelValInIntegralMat(x + 8 * w, y + 34 * h, w, h, IntegralMat)
                neg934 = self.getPixelValInIntegralMat(x + 9 * w, y + 34 * h, w, h, IntegralMat)
                neg1034 = self.getPixelValInIntegralMat(x + 10 * w, y + 34 * h, w, h, IntegralMat)
                neg1134 = self.getPixelValInIntegralMat(x + 11 * w, y + 34 * h, w, h, IntegralMat)
                neg1234 = self.getPixelValInIntegralMat(x + 12 * w, y + 34 * h, w, h, IntegralMat)
                neg1334 = self.getPixelValInIntegralMat(x + 13 * w, y + 34 * h, w, h, IntegralMat)
                neg1434 = self.getPixelValInIntegralMat(x + 14 * w, y + 34 * h, w, h, IntegralMat)
                neg1534 = self.getPixelValInIntegralMat(x + 15 * w, y + 34 * h, w, h, IntegralMat)
                neg1634 = self.getPixelValInIntegralMat(x + 16 * w, y + 34 * h, w, h, IntegralMat)
                neg1734 = self.getPixelValInIntegralMat(x + 17 * w, y + 34 * h, w, h, IntegralMat)
                neg1834 = self.getPixelValInIntegralMat(x + 18 * w, y + 34 * h, w, h, IntegralMat)
                neg1934 = self.getPixelValInIntegralMat(x + 19 * w, y + 34 * h, w, h, IntegralMat)
                featureVal[feature_index] = (( \
                                                         neg00 + neg10 + neg20 + neg30 + neg40 + neg50 + neg60 + neg70 + neg80 + neg90 + neg100 + neg110 + neg120 + neg130 + neg140 + neg150 + neg160 + neg170 + neg180 + neg190 + neg01 + neg11 + neg21 + neg31 + neg41 + neg51 + neg61 + neg71 + neg81 + neg91 + neg101 + neg111 + neg121 + neg131 + neg141 + neg151 + neg161 + neg171 + neg181 + neg191 + neg02 + neg12 + neg22 + neg32 + neg42 + neg52 + neg62 + neg72 + neg102 + neg112 + neg122 + neg132 + neg142 + neg152 + neg162 + neg172 + neg182 + neg192 + neg03 + neg13 + neg23 + neg33 + neg43 + neg53 + neg63 + neg113 + neg123 + neg133 + neg143 + neg153 + neg163 + neg173 + neg183 + neg193 + neg04 + neg14 + neg24 + neg34 + neg44 + neg54 + neg64 + neg114 + neg124 + neg134 + neg144 + neg154 + neg164 + neg174 + neg184 + neg194 + neg05 + neg15 + neg25 + neg35 + neg45 + neg55 + neg115 + neg125 + neg135 + neg145 + neg155 + neg165 + neg175 + neg185 + neg195 + neg06 + neg16 + neg26 + neg36 + neg46 + neg116 + neg126 + neg136 + neg146 + neg156 + neg166 + neg176 + neg186 + neg196 + neg07 + neg17 + neg27 + neg37 + neg47 + neg137 + neg147 + neg157 + neg167 + neg177 + neg187 + neg197 + neg08 + neg18 + neg28 + neg38 + neg48 + neg158 + neg168 + neg178 + neg188 + neg198 + neg09 + neg19 + neg29 + neg39 + neg159 + neg169 + neg179 + neg189 + neg199 + neg010 + neg110 + neg210 + neg310 + neg1510 + neg1610 + neg1710 + neg1810 + neg1910 + neg011 + neg111 + neg211 + neg311 + neg1511 + neg1611 + neg1711 + neg1811 + neg1911 + neg012 + neg112 + neg212 + neg312 + neg1412 + neg1512 + neg1612 + neg1712 + neg1812 + neg1912 + neg013 + neg113 + neg213 + neg1413 + neg1513 + neg1613 + neg1713 + neg1813 + neg1913 + neg014 + neg114 + neg214 + neg1414 + neg1514 + neg1614 + neg1714 + neg1814 + neg1914 + neg015 + neg115 + neg215 + neg415 + neg1515 + neg1615 + neg1715 + neg1815 + neg1915 + neg016 + neg116 + neg216 + neg316 + neg416 + neg716 + neg816 + neg1416 + neg1516 + neg1616 + neg1716 + neg1816 + neg1916 + neg017 + neg117 + neg217 + neg317 + neg717 + neg1417 + neg1517 + neg1617 + neg1717 + neg1817 + neg1917 + neg018 + neg118 + neg218 + neg1418 + neg1518 + neg1618 + neg1718 + neg1818 + neg1918 + neg019 + neg119 + neg1419 + neg1519 + neg1619 + neg1719 + neg1819 + neg1919 + neg020 + neg120 + neg1320 + neg1420 + neg1520 + neg1620 + neg1720 + neg1820 + neg1920 + neg021 + neg121 + neg1321 + neg1421 + neg1521 + neg1621 + neg1721 + neg1821 + neg1921 + neg022 + neg1322 + neg1422 + neg1522 + neg1622 + neg1722 + neg1822 + neg1922 + neg023 + neg1423 + neg1523 + neg1623 + neg1723 + neg1823 + neg1923 + neg024 + neg224 + neg324 + neg1424 + neg1524 + neg1624 + neg1724 + neg1824 + neg1924 + neg025 + neg125 + neg225 + neg325 + neg425 + neg1525 + neg1625 + neg1725 + neg1825 + neg1925 + neg026 + neg126 + neg226 + neg326 + neg426 + neg1626 + neg1726 + neg1826 + neg1926 + neg027 + neg127 + neg227 + neg327 + neg427 + neg1727 + neg1827 + neg1927 + neg028 + neg128 + neg228 + neg328 + neg428 + neg928 + neg1028 + neg1128 + neg1728 + neg1828 + neg1928 + neg029 + neg129 + neg229 + neg329 + neg829 + neg929 + neg1029 + neg1129 + neg1829 + neg1929 + neg030 + neg130 + neg230 + neg330 + neg730 + neg830 + neg930 + neg1030 + neg1130 + neg1230 + neg1330 + neg1830 + neg1930 + neg031 + neg131 + neg231 + neg531 + neg631 + neg731 + neg831 + neg931 + neg1031 + neg1131 + neg1231 + neg1331 + neg1431 + neg1831 + neg1931 + neg032 + neg132 + neg232 + neg532 + neg632 + neg732 + neg832 + neg932 + neg1032 + neg1132 + neg1232 + neg1332 + neg1432 + neg1832 + neg1932 + neg033 + neg133 + neg233 + neg333 + neg433 + neg533 + neg633 + neg733 + neg833 + neg933 + neg1033 + neg1133 + neg1233 + neg1333 + neg1433 + neg1533 + neg1633 + neg1833 + neg1933 + neg034 + neg134 + neg234 + neg334 + neg434 + neg534 + neg634 + neg734 + neg834 + neg934 + neg1034 + neg1134 + neg1234 + neg1334 + neg1434 + neg1534 + neg1634 + neg1734 + neg1834 + neg1934
                                             ) - (
                                                     pos82 + pos92 + pos73 + pos83 + pos93 + pos103 + pos74 + pos84 + pos94 + pos104 + pos65 + pos75 + pos85 + pos95 + pos105 + pos56 + pos66 + pos76 + pos86 + pos96 + pos106 + pos57 + pos67 + pos77 + pos87 + pos97 + pos107 + pos117 + pos127 + pos58 + pos68 + pos78 + pos88 + pos98 + pos108 + pos118 + pos128 + pos138 + pos148 + pos49 + pos59 + pos69 + pos79 + pos89 + pos99 + pos109 + pos119 + pos129 + pos139 + pos149 + pos410 + pos510 + pos610 + pos710 + pos810 + pos910 + pos1010 + pos1110 + pos1210 + pos1310 + pos1410 + pos411 + pos511 + pos611 + pos711 + pos811 + pos911 + pos1011 + pos1111 + pos1211 + pos1311 + pos1411 + pos412 + pos512 + pos612 + pos712 + pos812 + pos912 + pos1012 + pos1112 + pos1212 + pos1312 + pos313 + pos413 + pos513 + pos613 + pos713 + pos813 + pos913 + pos1013 + pos1113 + pos1213 + pos1313 + pos314 + pos414 + pos514 + pos614 + pos714 + pos814 + pos914 + pos1014 + pos1114 + pos1214 + pos1314 + pos315 + pos515 + pos615 + pos715 + pos815 + pos915 + pos1015 + pos1115 + pos1215 + pos1315 + pos1415 + pos516 + pos616 + pos916 + pos1016 + pos1116 + pos1216 + pos1316 + pos417 + pos517 + pos617 + pos817 + pos917 + pos1017 + pos1117 + pos1217 + pos1317 + pos318 + pos418 + pos518 + pos618 + pos718 + pos818 + pos918 + pos1018 + pos1118 + pos1218 + pos1318 + pos219 + pos319 + pos419 + pos519 + pos619 + pos719 + pos819 + pos919 + pos1019 + pos1119 + pos1219 + pos1319 + pos220 + pos320 + pos420 + pos520 + pos620 + pos720 + pos820 + pos920 + pos1020 + pos1120 + pos1220 + pos221 + pos321 + pos421 + pos521 + pos621 + pos721 + pos821 + pos921 + pos1021 + pos1121 + pos1221 + pos122 + pos222 + pos322 + pos422 + pos522 + pos622 + pos722 + pos822 + pos922 + pos1022 + pos1122 + pos1222 + pos123 + pos223 + pos323 + pos423 + pos523 + pos623 + pos723 + pos823 + pos923 + pos1023 + pos1123 + pos1223 + pos1323 + pos124 + pos424 + pos524 + pos624 + pos724 + pos824 + pos924 + pos1024 + pos1124 + pos1224 + pos1324 + pos525 + pos625 + pos725 + pos825 + pos925 + pos1025 + pos1125 + pos1225 + pos1325 + pos1425 + pos526 + pos626 + pos726 + pos826 + pos926 + pos1026 + pos1126 + pos1226 + pos1326 + pos1426 + pos1526 + pos527 + pos627 + pos727 + pos827 + pos927 + pos1027 + pos1127 + pos1227 + pos1327 + pos1427 + pos1527 + pos1627 + pos528 + pos628 + pos728 + pos828 + pos1228 + pos1328 + pos1428 + pos1528 + pos1628 + pos429 + pos529 + pos629 + pos729 + pos1229 + pos1329 + pos1429 + pos1529 + pos1629 + pos1729 + pos430 + pos530 + pos630 + pos1430 + pos1530 + pos1630 + pos1730 + pos331 + pos431 + pos1531 + pos1631 + pos1731 + pos332 + pos432 + pos1532 + pos1632 + pos1732 + pos1733 ) / (
                                                         700 * w * h))

                return featureVal

    def getPixelValInIntegralMat(self, x, y, w, h, integralMat):
        """
        x,y are the coordinates in the image matrix
        :param integralMat:
        :return:
        """
        if x == 0 and y == 0:
            return integralMat[y+h-1][x+w-1]
        elif x == 0:
            return integralMat[y+h-1][x+w-1] - integralMat[y-1][x+w-1]
        elif y == 0:
            return integralMat[y+h-1][x+w-1] - integralMat[y+h-1][x-1]
        else:
            return integralMat[y+h-1][x+w-1] + integralMat[y-1][x-1] \
                -  integralMat[y-1][x+w-1]   - integralMat[y+h-1][x-1]
